config/routes.rb
Rails.application.routes.draw do
   devise_for :users
   root 'homes#top'
  get "home/about" => "homes#about"
  get "searches" => "searches#search"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resources :book_comments, only: [:create, :destroy]
     resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  attachment :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
   def
     favorited_by?(user)
     favorites.where(user_id: user.id).exists?
   end

  def self.looks(search, word)
      if search == "perfect_match"
          @book = Book.where("title LIKE?", "#{word}")
      elsif search == "forward_match"
          @book = Book.where("title LIKE?", "%#{word}%")

      elsif search == "backward_match"
          @book = Book.where("title LIKE?", "%#{word}%")

      elsif search == "partial_match"
          @book = Book.where("title LIKE?", "%#{word}%")

      else
         @book = Book.all
      end
  end


  validates :title, presence: true
  validates :body, presence: true, length:{maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
   belongs_to :user
   belongs_to :book

   validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follows, class_name: 'User'
  belongs_to :followers, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         attachment :profile_image
         has_many :book_comments, dependent: :destroy
         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy

         has_many :relationships, foreign_key: :follows_id
         has_many :follows, through: :relationships, source: :followers
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :followers_id, dependent: :destroy
         has_many :followers, through: :reverse_of_relationships, source: :follows, dependent: :destroy

         def is_followed_by?(user)
           reverse_of_relationships.find_by(follows_id: user.id).present?
         end

         def self.looks(search, word)
          if search == "perfect_match"
              @user = User.where("name LIKE?", "#{word}")
          elsif search == "forward_match"
              @user = User.where("name LIKE?", "%#{word}%")

          elsif search == "backward_match"
              @user = User.where("name LIKE?", "%#{word}%")

          elsif search == "partial_match"
              @user = User.where("name LIKE?", "%#{word}%")

          else
              @user = User.all
          end
         end

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction,  length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [ :top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  add_flash_types :success, :info, :warning, :danger
  
  protected
  def after_sign_in_path_for(resource)
    user_path(resource)# ログイン後に遷移するpathを設定
  end
  
  def after_sign_out_path_for(resource)
    root_path(resource)
  end
  
  def move_to_index
    unless user_signed_in? == current_user.name
      redirect_to root_path
    end
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    # redirect_to book_path(book.id)
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(params[:id]).destroy
    # redirect_to book_path(book.id)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book)
    flash[:notice] = "You have created book successfully."
    else
    render:"index"
    end
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @myuser = current_user
    @book_comment = BookComment.new
    @book_comments = BookComment.all
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
    if @user != @book.user
      redirect_to books_path
    end
  end

  def update
    @user =  current_user
    @book = Book.find(params[:id])
    flash[:notice] = "You have updated book successfully."
      if @book.update(book_params)
      redirect_to book_path (@book)
      else
      render:edit
      end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
      redirect_to books_path
    @user = current_user
    if @user != @book.user
      redirect_to books_path
    end
  end


  private
  def book_params
      params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back(fallback_location: root_path)ajax追加のため削除
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back(fallback_location: root_path)ajax追加のため削除
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @user = current_user
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    # 検索モデル
    @word = params[:word]

    if @range == "user"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @users = User.where.not(id: current_user.id)
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
    @users = User.all
    # @users = User.where.not(id: current_user.id)
  end

  # 応用課題４で追加
  def follows
    user=User.find(params[:id])
    @users=user.follows
  end

  def followers
    user=User.find(params[:id])
    @users=user.followers
  end

  def create
    @user= User.new(user_params)
    @user.save
     redirect_to user_params_id
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
    redirect_to user_path(current_user)
    end
  end

  def update
    @user= User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path (@user)
    else
    render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end


   private
    def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comment.html.erb
<% book.book_comments.each do |book_comment| %>
        <tr><td><p> <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60,fallback:"no_image.jpg" %></p></td>
         <td><%= book_comment.user.name %></td>
　　　　 <td><%= book_comment.comment %></td>
         <% if book_comment.user == current_user %>
          <td><button type="button" class="btn btn-danger"><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true %></button> </td>
          <% end %>
<% end %>
        </tr>

app/views/book_comments/create.js.erb
$(".book_comment").html("<%= j(render "book_comments/book_comment", book: @book) %>");

$("textarea").val('')

app/views/book_comments/destroy.js.erb
$(".book_comment").html("<%= j(render "book_comments/book_comment", book: @book) %>");

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">

<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
<% end %>

<%= form_with model: @book, local:true do |f| %>
 <h4>title</h4>
   <%= f.text_field :title %>
  <h4>Opinion</h4>
    <%= f.text_area :body %>
  <br>
  <%= f.submit 'Update Book' %>
 <% end %>


<%= link_to "Show",book_path(@book) %>
|
<%= link_to "Back",books_path %>

 </div>
  </div>
</div>

app/views/books/index.html.erb
<main>
<div class="container px-5 px-sm-0">

<div class= "row">

<div class="col-md-3">
  <%= render "users/users",user: @user, book: @book %>

</div>

<div class= "col-md-8 offset-md-1">
 <%= render "searches/search" %>
<h2>Books</h2>
<table class= "table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <tr>
      <% @books.each do |book| %>
      <td>
      <%= link_to user_path(book.user) do %>
      <%=  attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
       <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      <td class=<%= "favorite_buttons_"+ book.id.to_s %>>
　　　<%= render "favorites/favorite", book: book %>
　　  </td>
  </td>
      <td><p><%= link_to "#{book.book_comments.count} コメント",  book_path(book.id) %></p></td>
     </tr>
       <% end %>
  </tbody>
</table>
</div>
</div>
</div>
</main>

app/views/books/show.html.erb
<div class= "container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "/users/users",user: @user, book: @newbook %>
    </div>

<div class = "col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">

</div>
    <tbody>
      <tr>
        <td>
        <%= link_to user_path(@book.user_id) do %>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60,fallback:"no_image.jpg" %>
　　　　<br>
　　　　<%= @book.user.name %>
        <% end %>
        </td>

        <td><%= link_to book_path(@book.id) do %>
        <%= @book.title %><% end %>
        </td>

        <td><%= @book.body %></td>
          <td class=<%= "favorite_buttons_"+ @book.id.to_s %>>
　　　   <%= render "favorites/favorite", book: @book %>
　　      </td>
        <td> <% if @book.user == current_user %>
        <%= link_to "Edit", edit_book_path(@book),class:"btn btn-success btn-sm btn-block mb-3" %>
        <% end %>
        </td>
        <td> <% if @book.user == current_user %>
            <%= link_to "Destroy", book_path, method: :delete, data:{ confirm: '本当に消しますか？' },class:"btn btn-danger btn-sm btn-block mb-3" %>
            <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class = "col-md-8 offset-md-1">
    <table class="table">
      <tbody>
         <td class= "book_comment">
　　　    <%= render "book_comments/book_comment", book: @book %>
        </td>
        </tbody>
        </table>
  </div>
      <div>
     <td><%= form_with(model: [@book,@book_comment], remote: true) do |f| %>
        <%= f.text_area :comment, placeholder: "コメントをここに", class: "col-8" %>
        <%= f.submit "送信する" %>
      <% end %>
　　　</td>
      </div>
　</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
        ♥<%= book.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book), method: :post, remote: true do %>
        ♡<%= book.favorites.count %> いいね
      <% end %>
    </p>
<% end %>

app/views/favorites/create.js.erb
$(".favorite_buttons_"+ <%= @book.id %>).html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$(".favorite_buttons_"+ <%= @book.id %>).html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/users/_users.html.erb
<h2>User info</h2>
<% if book.errors.any? %>
  <%= book.errors.count %>件のerrorが発生しました
  <% book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= attachment_image_tag user, :profile_image, :fill, 60, 60,fallback:"no_image.jpg" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>

    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
      <tr>
      <th>follows</th>
      <th><%= link_to user.follows.count,follows_user_path(user.id)%></th>
      <tr>
        <th>followers</th>
      <th><%= link_to user.followers.count,followers_user_path(user.id)%></th>
      </tr>
    </tr>
  </tbody>
</table>
  <% if user != current_user %>
    <% if user.is_followed_by?(current_user) %>
      <div class="row">
        <%= link_to 'フォロー外す', user_relationships_path(user.id), class: "btn btn-praimary", method: :delete %>
      </div>
    <% else %>
      <div class="row">
        <%= link_to 'フォローする', user_relationships_path(user.id), class: "btn btn-success", method: :post %>
      </div>
    <% end %>
    <% else %>
      <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
       <!--edit_user_path(current_user.id) do -->
  <% end %>

<h1>New book</h1>
<%= form_with model:book, local:true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        
<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <% @user.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
<% end %>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <div class="form-group">
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  </div>
  <div class="form-group">
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60,fallback: "no_image.jpg" %>
  <label for="inputImage">ProfileImage</label>
    <%= f.attachment_field :profile_image %>
  </div>
  <div class="form-group">
    <%= f.text_field :introduction, autofocus: true, id:"inputName", placeholder:"自己紹介"%>
    </div>
    <%= f.submit "Update User" %>
<% end %>
</div>
</div>
</div>
</main>

app/views/users/followers.html.erb
<div class= "col-md-8 offset-md-1">
<h2>Follower Users</h2>
<table class= "table table-hover table-inverse">

  <thead>
    <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @users.each do |user| %>
      <tr>
      <td> <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
      </td>
      <td><%= user.name %></td>
       <td><p>フォロー数<%= user.follows.count %></p></td>
       <td><p>フォロワー数<%= user.followers.count %></p></td>
      <td><%= link_to "Show", user_path(user) %></td>
      </tr>
       <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/users/follows.html.erb
<div class= "col-md-8 offset-md-1">
<h2>Follows Users</h2>
<table class= "table table-hover table-inverse">

   <thead>
    <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @users.each do |user| %>
      <tr>
      <td> <%=  attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
      </td>
      <td><%= user.name %></td>
       <td><p>フォロー数<%= user.follows.count %></p></td>
       <td><p>フォロワー数<%= user.followers.count %></p></td>
      <td><%= link_to "Show", user_path(user) %></td>
    　</tr>
       <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/users/index.html.erb
<main>

<div class="container px-5 px-sm-0">

<div class= "row">

<div class="col-md-3">
  <%= render "users/users",user: @user, book: @book %>
</div>

<div class= "col-md-8 offset-md-1">
  <%= render "searches/search" %>
<h2>Users</h2>
<table class= "table table-hover table-inverse">

  <thead>
    <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    　<tr>
        <td>
        　<%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
        </td>
        <td><%= user.name %></td>
        <td><p>フォロー数<%= user.follows.count %></p></td>
        <td><p>フォロワー数<%= user.followers.count %></p></td>
        <td>
          <% if user != current_user %>
          　<% if user.is_followed_by?(current_user) %>
              <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
            <% else%>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
  　　  　</td>
  　　　　　<td><%= link_to "Show", user_path(user) %></td>
　　　</tr>
    <% end %>
  </tbody>

</table>
</div>
</div>
</div>
</main>

app/views/users/show.html.erb
<div class= "container px-5 px-sm-0">
  <div class="row">
<div class="col-md-3">
  </p>
  <%= render "users",user: @user, book: @book %>
</div>

<div class= "col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book|  %>
      <tr>
      <td>
      <%= link_to user_path(@user) do %>
      <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "no_image.jpg" %>
      <% end %>
      </td>
      <td><%= link_to book.title, book_path(book) %>
      </td>
      <td><%= book.body %></td>
      </tr>
      <% end %>
  </tbody>
  </table>
</div>
 </div>
</div>