config/routes.rb
Rails.application.routes.draw do
   devise_for :users
   root 'homes#top'
  get "home/about" => "homes#about"
  get "searches" => "searches#search"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resources :book_comments, only: [:create, :destroy]
     resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  attachment :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
   def
     favorited_by?(user)
     favorites.where(user_id: user.id).exists?
   end

  def self.looks(search, word)
      if search == "perfect_match"
          @book = Book.where("title LIKE?", "#{word}")
      elsif search == "forward_match"
          @book = Book.where("title LIKE?", "%#{word}%")

      elsif search == "backward_match"
          @book = Book.where("title LIKE?", "%#{word}%")

      elsif search == "partial_match"
          @book = Book.where("title LIKE?", "%#{word}%")

      else
         @book = Book.all
      end
  end


  validates :title, presence: true
  validates :body, presence: true, length:{maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
   belongs_to :user
   belongs_to :book

   validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follows, class_name: 'User'
  belongs_to :followers, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         attachment :profile_image
         has_many :book_comments, dependent: :destroy
         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy

         has_many :relationships, foreign_key: :follows_id
         has_many :follows, through: :relationships, source: :followers
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :followers_id, dependent: :destroy
         has_many :followers, through: :reverse_of_relationships, source: :follows, dependent: :destroy

         def is_followed_by?(user)
           reverse_of_relationships.find_by(follows_id: user.id).present?
         end

         def self.looks(search, word)
          if search == "perfect_match"
              @user = User.where("name LIKE?", "#{word}")
          elsif search == "forward_match"
              @user = User.where("name LIKE?", "%#{word}%")

          elsif search == "backward_match"
              @user = User.where("name LIKE?", "%#{word}%")

          elsif search == "partial_match"
              @user = User.where("name LIKE?", "%#{word}%")

          else
              @user = User.all
          end
         end

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction,  length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [ :top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  add_flash_types :success, :info, :warning, :danger
  
  protected
  def after_sign_in_path_for(resource)
    user_path(resource)# ログイン後に遷移するpathを設定
  end
  
  def after_sign_out_path_for(resource)
    root_path(resource)
  end
  
  def move_to_index
    unless user_signed_in? == current_user.name
      redirect_to root_path
    end
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book)
    flash[:notice] = "You have created book successfully."
    else
    render:"index"
    end
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @myuser = current_user
    @book_comment = BookComment.new
    @book_comments = BookComment.all
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
    if @user != @book.user
      redirect_to books_path
    end
  end

  def update
    @user =  current_user
    @book = Book.find(params[:id])
    flash[:notice] = "You have updated book successfully."
      if @book.update(book_params)
      redirect_to book_path (@book)
      else
      render:edit
      end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
      redirect_to books_path
    @user = current_user
    if @user != @book.user
      redirect_to books_path
    end
  end


  private
  def book_params
      params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back(fallback_location: root_path)ajax追加のため削除
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back(fallback_location: root_path)ajax追加のため削除
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @user = current_user
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    # 検索モデル
    @word = params[:word]

    if @range == "user"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @users = User.where.not(id: current_user.id)
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
    @users = User.all
    # @users = User.where.not(id: current_user.id)
  end

  # 応用課題４で追加
  def follows
    user=User.find(params[:id])
    @users=user.follows
  end

  def followers
    user=User.find(params[:id])
    @users=user.followers
  end

  def create
    @user= User.new(user_params)
    @user.save
     redirect_to user_params_id
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
    redirect_to user_path(current_user)
    end
  end

  def update
    @user= User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path (@user)
    else
    render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end


   private
    def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<main>

<div class= "container">
  <div class="row">
<h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
</div>
</div>
<!--<div class="container mt-5">-->
<!--  <div class="row">-->
<!--  <div class="mx-auto">-->
<!--  <footer>CopyRight Infratop.inc</footer>-->

<!--  </div>-->
<!--  </div>-->
<!--  </div>-->

<!--  </main>-->

app/views/homes/top.html.erb
<main>
<div class= "container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>

<p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>

<p>you can share and exchange your opinions , inpressions , and emotions</p>

<p>about various books!</p>

<div class="btn-wrapper col-10 mx-auto">
   <div class="row">
<%= link_to "Log in",new_user_session_path , class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
</div>

 <div class="row">
<%= link_to "Sign Up", new_user_registration_path , class:"btn btn-success btn-sm btn-block mb-3 sign_up" %>
</div>
</div>
</div>
</div>
</div>
</main>

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <div class= "search_form">
    <%= form_with url: searches_path, method: :get, local: true do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['user'],['Book']]) %>
      <%= f.select :search, options_for_select([['完全一致','perfect_match'], ['前方一致','forward_match'],['後方一致','backword_match'],['部分一致','partial_match']]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<h2>Books search for <%= @word %> </h2>
<table class= "table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
    <th>title</th>
    <th>opinion</th>
    <th colspan="2"></th>
    </tr>
  </thead>
  <% if @range == "user" %>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60,fallback:"no_image.jpg" %></td>
      </tr>
      <% end %>
    </tbody>

    <% else %>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= attachment_image_tag book.user, :profile_image, :fill, 60, 60,fallback:"no_image.jpg" %></td>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
    </tbody>
    <% end %>
</table>