config/routes.rb
Rails.application.routes.draw do
   devise_for :users
   root 'homes#top'
  get "home/about" => "homes#about"
  get "searches" => "searches#search"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resources :book_comments, only: [:create, :destroy]
     resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  attachment :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
   def
     favorited_by?(user)
     favorites.where(user_id: user.id).exists?
   end

  def self.looks(search, word)
      if search == "perfect_match"
          @book = Book.where("title LIKE?", "#{word}")
      elsif search == "forward_match"
          @book = Book.where("title LIKE?", "%#{word}%")

      elsif search == "backward_match"
          @book = Book.where("title LIKE?", "%#{word}%")

      elsif search == "partial_match"
          @book = Book.where("title LIKE?", "%#{word}%")

      else
         @book = Book.all
      end
  end


  validates :title, presence: true
  validates :body, presence: true, length:{maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
   belongs_to :user
   belongs_to :book

   validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follows, class_name: 'User'
  belongs_to :followers, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         attachment :profile_image
         has_many :book_comments, dependent: :destroy
         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy

         has_many :relationships, foreign_key: :follows_id
         has_many :follows, through: :relationships, source: :followers
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :followers_id, dependent: :destroy
         has_many :followers, through: :reverse_of_relationships, source: :follows, dependent: :destroy

         def is_followed_by?(user)
           reverse_of_relationships.find_by(follows_id: user.id).present?
         end

         def self.looks(search, word)
          if search == "perfect_match"
              @user = User.where("name LIKE?", "#{word}")
          elsif search == "forward_match"
              @user = User.where("name LIKE?", "%#{word}%")

          elsif search == "backward_match"
              @user = User.where("name LIKE?", "%#{word}%")

          elsif search == "partial_match"
              @user = User.where("name LIKE?", "%#{word}%")

          else
              @user = User.all
          end
         end

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction,  length: {maximum: 50}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book)
    flash[:notice] = "You have created book successfully."
    else
    render:"index"
    end
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @myuser = current_user
    @book_comment = BookComment.new
    @book_comments = BookComment.all
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
    if @user != @book.user
      redirect_to books_path
    end
  end

  def update
    @user =  current_user
    @book = Book.find(params[:id])
    flash[:notice] = "You have updated book successfully."
      if @book.update(book_params)
      redirect_to book_path (@book)
      else
      render:edit
      end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
      redirect_to books_path
    @user = current_user
    if @user != @book.user
      redirect_to books_path
    end
  end


  private
  def book_params
      params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @user = current_user
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    # 検索モデル
    @word = params[:word]

    if @range == "user"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @users = User.where.not(id: current_user.id)
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
    @users = User.all
    # @users = User.where.not(id: current_user.id)
  end

  # 応用課題４で追加
  def follows
    user=User.find(params[:id])
    @users=user.follows
  end

  def followers
    user=User.find(params[:id])
    @users=user.followers
  end

  def create
    @user= User.new(user_params)
    @user.save
     redirect_to user_params_id
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
    redirect_to user_path(current_user)
    end
  end

  def update
    @user= User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path (@user)
    else
    render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end


   private
    def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">


      <li>
        <i class="fas fa-book-open"><strong><%= link_to "Bookers", root_path %></strong></i>
      </li>

      <div class="collapse navbar-collapse" id="navbarNavDropdown"></div>
      <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>

      <li class=Home>
        <i class="fas fa-home"><%= link_to "Home",user_path(current_user.id) %></i>
      </li>

     <li class=user>
      <i class="fas fa-users"><%= link_to 'Users', users_path %></i>
      </li>

       <li class=Books>
      <i class="fas fa-book-open"><%= link_to 'Books', books_path %></i>
      </li>

      <li class=logout>
        <i class="fas fa-sign-out-alt"><%= link_to "logout", destroy_user_session_path, method: :delete %></i>
      </li>

    <% else %>

     <li class=Home>
        <i class="fas fa-home"><%= link_to "Home",root_path %></i>
      </li>

      <li class=about>
        <i class="fas fa-link"> <%= link_to "about", home_about_path %></i>
      </li>


      <li calss=signup>
        <i class="fas fa-user-plus"><%= link_to "sign up", new_user_registration_path %></i>
      </li>

      <li class=login>
        <i class="fas fa-sign-in-alt"><%= link_to "login", new_user_session_path %></i>
      </li>

   <% end %>
    </ul>
    </div>
    </nav>
    </header>
    <%= notice %>
    <%= yield %>

<div class="container mt-5">
  <div class="row">
  <div class="mx-auto">
  <footer>CopyRight Infratop.inc</footer>
  </div>
  </div>
  </body>
</html>